user-registration:
  max-attempts: 3
  expiration: 1440
  tokenSize: 6

user-security:
  jwtSecret : ======================userServiceKey======================
  jwtExpirationMs: 900000
  jwtCookie: user-jwt-token

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic


spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverclass: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console.enabled: true

  liquibase:
    enabled: true
    user: sa
    password:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  profiles:
    active: dev

    cloud:
    loadbalancer:
      ribbon:
        enable: true



