spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverclass: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto : update
  h2:
    console.enabled: true

  liquibase:
    enabled: true
    user: sa
    password:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  profiles:
    active: dev