package com.accenture.userservice.model;

public enum ErrorCodeEnum {
  EMAIL_EXISTS, EMAIL_INVALID,USER_NOT_FOUND,ORGANISATION_NOT_FOUND,
  ORGANISATION_DOMAIN_EXISTS,SUCCESS, TOTAL_ATTEMPTS_OVER,TOKEN_MISMATCH,CODE_EXPIRED;
}